// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/Provider/Dialog/index.vue')['default']
    Message: typeof import('./src/components/Provider/Message/index.vue')['default']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Notification: typeof import('./src/components/Provider/Notification/index.vue')['default']
    Provider: typeof import('./src/components/Provider/index.vue')['default']
  }
}

export { }
