// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AntdMenuFoldOutlined: typeof import('~icons/ant-design/menu-fold-outlined')['default']
    AntdMenuUnfoldOutlined: typeof import('~icons/ant-design/menu-unfold-outlined')['default']
    AntdReloadOutlined: typeof import('~icons/ant-design/reload-outlined')['default']
    Dialog: typeof import('./../src/components/Provider/Dialog/index.vue')['default']
    Mask: typeof import('./../src/components/Mask/index.vue')['default']
    Message: typeof import('./../src/components/Provider/Message/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Notification: typeof import('./../src/components/Provider/Notification/index.vue')['default']
    Overlay: typeof import('./../src/components/Overlay/index.vue')['default']
    Provider: typeof import('./../src/components/Provider/index.vue')['default']
  }
}

export { }
